services:
  defindex-soroban:
    image: esteblock/soroban-preview:21.0.0_node_20@sha256:d3627781219149842dde9afc93c66010d8f3e4a3022252f3668141dee3eb39c1
    container_name: defindex-soroban
    volumes:
      - .:/workspace
    ipc: host
    networks:
      - defindex-network
    command: tail -f /dev/null
    ports:
      - "3000:3000"
      - "3010:3010"
      - "3050:3050"

  stellar:
    image: stellar/quickstart:v426-latest-amd64@sha256:274395daab6fa8033b9213f152d56699358917fb01d7c7e95392a37fc00c9d01
    container_name: stellar
    networks:
      - defindex-network
    ports:
      - "8000:8000"
    command: --local --enable-soroban-rpc --enable-soroban-diagnostic-events
    stdin_open: true
    tty: true

networks:
  defindex-network:
    driver: bridge
